### ISSUE TITLE
NullReferenceException in Commit

### ISSUE THREAD

**Issue by SebastianStehle** [LSViana/ydotnet#41]
Hi,

I am testing a scenario where I want to push a notification to another document when a new comment has been created.

https://github.com/SebastianStehle/ydotnet/blob/main/Demo/Callback.cs#L50

But I get a NullReferenceException in the commit method and the following error:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BorrowMutError', yffi\src\lib.rs:466:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src/result.rs:1076:23
   4: ydoc_observe_updates_v1
             at D:\_other\y-crdt\yffi\src\lib.rs:460:20
```

Have you seen this before? I have no idea about rust and cannot narrow it down yet.

**Comment by SebastianStehle** [comment]
Sorry, it was my failure.
